name: general-tests
# Builds release dockers for ops-release, tagging them with the ops tag given

on: [push, pull_request]

jobs:
  general-tests-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        github-server-url: https://github.com/dogusyuksel/extended-grep.git
        lfs: true

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Project Docker
      uses: docker/build-push-action@v5
      with:
        load: true
        tags: |
          project_docker:master
        context: .
        file: Dockerfile
        pull: false
        push: false
        provenance: false

    - name: Run Check
      run: |
         ./run_docker.sh "python3 egrep.py -f test.txt --keywords RX,errors --notkeysensitive --elementat 2 --typeint"

    - name: Flake8 Check
      run: |
         ./run_docker.sh "run_flake8.sh"

    - name: Pytest Check
      run: |
         ./run_docker.sh "run_pytest.sh"
